name: 'zaalima_retail_forecasting'
version: '1.0.0'
config-version: 2

# Connects the project structure to your local profile mapping
profile: 'zaalima_retail'

# Directs dbt to use the dev configuration target mapping
flags:
  target: dev

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  zaalima_retail_forecasting:
    staging:
      +materialized: view
    marts:
      +materialized: table
