SELECT COUNT(*)
FROM RETAIL_DEMAND.PUBLIC.RAW_CALENDAR;
SELECT COUNT(*)
FROM RETAIL_DEMAND.PUBLIC.RAW_SALES_TRAIN_VALIDATION;
SELECT COUNT(*)
FROM RETAIL_DEMAND.PUBLIC.RAW_SELL_PRICES;
SELECT COUNT(*)
FROM RETAIL_DEMAND.PUBLIC.RAW_SALES_TRAIN_EVALUATION;

DESCRIBE TABLE RETAIL_DEMAND.PUBLIC.RAW_SALES_TRAIN_VALIDATION;
